//
//  WineGlossaryData.swift
//  VinoBytes
//
//  Created by Logan Rausch on 6/3/24.
//

import Foundation

struct GlossaryEntry {
    let term: String
    let definition: String
    let additionalInfo: String
}

struct WineGlossaryData {
    static let terms: [GlossaryEntry] = [
        GlossaryEntry(term: "Acidity", definition: "The quality of wine that gives it its crispness and freshness.", additionalInfo: "Acidity is a crucial component of a wine's structure and balance."),
        GlossaryEntry(term: "Amphora", definition: "A type of clay vessel used for fermenting and aging wine.", additionalInfo: "Amphorae have been used since ancient times and are seeing a resurgence in modern winemaking."),
        GlossaryEntry(term: "Aroma", definition: "Aroma refers to the smells that come from the grapes and fermentation process.", additionalInfo: "In young wines, these are typically fruity or floral."),
        GlossaryEntry(term: "Balance", definition: "The harmonious relationship between a wine's elements (acidity, tannin, alcohol, and fruit).", additionalInfo: "A well-balanced wine has no single element overpowering the others."),
        GlossaryEntry(term: "Blanc de Blancs", definition: "A sparkling wine made exclusively from white grapes.", additionalInfo: "Commonly used in Champagne."),
        GlossaryEntry(term: "Blanc de Noirs", definition: "A sparkling wine made from red grapes.", additionalInfo: "The juice is usually pressed off the skins quickly to avoid color transfer."),
        GlossaryEntry(term: "Bouquet", definition: "Bouquet refers to the complex aromas that develop in wine after it has aged.", additionalInfo: "It is different from aroma, which is more associated with young wines."),
        GlossaryEntry(term: "Chaptalization", definition: "The process of adding sugar to grape juice before fermentation to increase the alcohol content.", additionalInfo: "This practice is often used in cooler climates where grapes may not ripen fully."),
        GlossaryEntry(term: "Claret", definition: "Claret is a term used in Britain to describe red Bordeaux wine.", additionalInfo: "It is traditionally a blend of several grape varieties."),
        GlossaryEntry(term: "Clos", definition: "A French term for a walled vineyard.", additionalInfo: "Clos is commonly used in Burgundy."),
        GlossaryEntry(term: "Cremant", definition: "A French term for sparkling wines made outside of the Champagne region.", additionalInfo: "Cremant wines are made using the same traditional method as Champagne."),
        GlossaryEntry(term: "Cru", definition: "Cru is a French term that means 'growth' and refers to a vineyard or group of vineyards of recognized quality.", additionalInfo: "It is often used in regions like Bordeaux and Burgundy."),
        GlossaryEntry(term: "Decanting", definition: "Decanting is the process of pouring wine from its bottle into a decanter.", additionalInfo: "This helps to separate the wine from any sediment and allows it to breathe."),
        GlossaryEntry(term: "Dry", definition: "Dry wine has little to no residual sugar, making it not sweet.", additionalInfo: "It is the opposite of sweet wine."),
        GlossaryEntry(term: "Enology", definition: "Enology is the science and study of wine and winemaking.", additionalInfo: "It encompasses everything from the vineyard to the finished product."),
        GlossaryEntry(term: "Estate Bottled", definition: "Indicates that the wine was made and bottled on the winery's property.", additionalInfo: "All the grapes used must come from the estate's vineyards."),
        GlossaryEntry(term: "Fermentation", definition: "The process by which yeast converts sugars in grape juice into alcohol and carbon dioxide.", additionalInfo: "Fermentation is essential to the production of wine."),
        GlossaryEntry(term: "Finish", definition: "Finish is the taste that lingers in the mouth after swallowing.", additionalInfo: "A long finish is often a sign of a high-quality wine."),
        GlossaryEntry(term: "Fortified Wine", definition: "Wine to which a distilled spirit, usually brandy, has been added.", additionalInfo: "Examples include Port, Sherry, and Madeira."),
        GlossaryEntry(term: "Hybrid", definition: "A grape variety that is a cross between two different species of grapevine.", additionalInfo: "Hybrids are often bred for disease resistance and hardiness."),
        GlossaryEntry(term: "Late Harvest", definition: "Wines made from grapes that are picked later than usual, resulting in higher sugar levels.", additionalInfo: "These wines are often sweet."),
        GlossaryEntry(term: "Lees", definition: "Sediment consisting of dead yeast cells and other particles that settles at the bottom of a wine tank or barrel.", additionalInfo: "Lees aging can add complexity to the wine."),
        GlossaryEntry(term: "Legs", definition: "Legs are the streaks of wine that form on the inside of a glass after swirling.", additionalInfo: "They can give an indication of the wine's alcohol content."),
        GlossaryEntry(term: "Maceration", definition: "The process of soaking grape skins in their juice to extract color, tannins, and flavors.", additionalInfo: "Maceration is a key step in red wine production."),
        GlossaryEntry(term: "Malolactic Fermentation", definition: "Malolactic fermentation is a process where malic acid in wine is converted to lactic acid.", additionalInfo: "This can soften the wine and add complexity."),
        GlossaryEntry(term: "Meritage", definition: "A term used in the United States for Bordeaux-style red and white wines.", additionalInfo: "Meritage wines must be made from specific grape varieties."),
        GlossaryEntry(term: "Microclimate", definition: "The climate of a small, specific area within a vineyard.", additionalInfo: "Microclimate can significantly affect the quality of grapes."),
        GlossaryEntry(term: "Négociant", definition: "A wine merchant who buys grapes, juice, or finished wine from growers and winemakers.", additionalInfo: "Négociants then bottle and sell the wine under their own label."),
        GlossaryEntry(term: "Oaked", definition: "Oaked wine has been aged in oak barrels, imparting flavors and aromas.", additionalInfo: "These can include vanilla, spice, and toast."),
        GlossaryEntry(term: "Old Vine", definition: "Refers to wines made from grapes grown on older vines, typically 20 years or older.", additionalInfo: "Old vines often produce lower yields of higher quality fruit."),
        GlossaryEntry(term: "Oxidation", definition: "Oxidation occurs when wine is exposed to air and starts to spoil.", additionalInfo: "This can cause the wine to lose its freshness and develop off-flavors."),
        GlossaryEntry(term: "Phylloxera", definition: "Phylloxera is a tiny insect that attacks the roots of grapevines.", additionalInfo: "It devastated European vineyards in the 19th century."),
        GlossaryEntry(term: "Pomace", definition: "The solid remains of grapes after pressing, including skins, pulp, seeds, and stems.", additionalInfo: "Pomace can be used for making grappa or as compost."),
        GlossaryEntry(term: "Racking", definition: "The process of moving wine from one container to another to separate it from sediment.", additionalInfo: "Racking helps clarify the wine."),
        GlossaryEntry(term: "Residual Sugar", definition: "The amount of sugar remaining in a wine after fermentation.", additionalInfo: "It determines the sweetness of the wine."),
        GlossaryEntry(term: "Sediment", definition: "Sediment is the solid particles that settle at the bottom of a wine bottle.", additionalInfo: "It is often found in older red wines and should be separated by decanting."),
        GlossaryEntry(term: "Sommelier", definition: "A sommelier is a wine steward responsible for wine service and pairing in a restaurant.", additionalInfo: "They are trained and knowledgeable in all aspects of wine."),
        GlossaryEntry(term: "Sur Lie Aging", definition: "A winemaking technique where wine is left to age on its yeast lees, adding complexity and texture.", additionalInfo: "Common in the production of certain white wines, like Muscadet."),
        GlossaryEntry(term: "Sustainable Viticulture", definition: "Farming practices that are environmentally responsible and economically viable.", additionalInfo: "These practices aim to balance the needs of the present without compromising future generations."),
        GlossaryEntry(term: "Tannin", definition: "Naturally occurring compounds in grape skins, seeds, and stems that provide structure and ageability to wine.", additionalInfo: "Tannins are most prominent in red wines and contribute to their astringency."),
        GlossaryEntry(term: "Terroir", definition: "The set of all environmental factors that affect a crop's phenotype, including unique environment contexts, farming practices and a crop's specific growth habitat.", additionalInfo: "Terroir gives wine its unique qualities."),
        GlossaryEntry(term: "Ullage", definition: "The space between the wine and the top of the wine container in barrels and bottles.", additionalInfo: "This space allows for some expansion and contraction of the wine due to temperature changes."),
        GlossaryEntry(term: "Unfiltered", definition: "Wine that has not been filtered to remove solid particles before bottling.", additionalInfo: "Unfiltered wines can have more texture and flavor complexity."),
        GlossaryEntry(term: "Varietal", definition: "Refers to wines made primarily from a single named grape variety.", additionalInfo: "Common examples include Chardonnay, Merlot, and Syrah."),
        GlossaryEntry(term: "Véraison", definition: "The stage of grape ripening when the grapes change color and begin to soften.", additionalInfo: "This is an important indicator in determining the harvest time."),
        GlossaryEntry(term: "Vinification", definition: "The process of turning grapes into wine, involving fermentation and aging.", additionalInfo: "Each step of vinification can influence the final taste and quality of the wine."),
        GlossaryEntry(term: "Vintage", definition: "Refers to the year the grapes were harvested and used to produce a particular wine.", additionalInfo: "Vintage can greatly affect wine quality due to the differing conditions each year."),
        GlossaryEntry(term: "Viticulture", definition: "The science, production, and study of grapes.", additionalInfo: "It focuses primarily on the process of grape cultivation."),
        GlossaryEntry(term: "Yeast", definition: "Microorganisms that are essential to the fermentation process, converting sugars in grape juice into alcohol and carbon dioxide.", additionalInfo: "Different strains of yeast can impart varying flavors and aromas."),
        GlossaryEntry(term: "Yield", definition: "The amount of grapes or wine produced in a specific area.", additionalInfo: "Lower yields are often associated with higher quality wine production."),
        GlossaryEntry(term: "Zymology", definition: "The science of fermentation in wine.", additionalInfo: "Also known as enology, it studies the biochemical process and its role in winemaking."),
        GlossaryEntry(term: "Angel's Share", definition: "The portion of wine or spirits that evaporates from oak barrels during aging.", additionalInfo: "Commonly mentioned in the context of barrel-aged wines and spirits like whisky."),
        GlossaryEntry(term: "Appassimento", definition: "A traditional Italian method of drying harvested grapes to concentrate their juice.", additionalInfo: "Primarily used in the Veneto region to produce rich, flavorful wines like Amarone."),
        GlossaryEntry(term: "Bâtonnage", definition: "The process of stirring wine lees in a barrel to enhance flavor and texture.", additionalInfo: "This technique is often used in the production of creamy, complex white wines."),
        GlossaryEntry(term: "Biodynamic", definition: "A method of organic farming involving homeopathic treatments and following an agricultural calendar.", additionalInfo: "Emphasizes a holistic approach to viticulture and enology."),
        GlossaryEntry(term: "Brix", definition: "A measure of the sugar content of grapes, indicating the degree of potential alcohol level in wine.", additionalInfo: "It helps vintners decide the optimal time for harvest."),
        GlossaryEntry(term: "Capsule", definition: "The protective sleeve made of metal or plastic that covers the cork and neck of a wine bottle.", additionalInfo: "Serves both decorative and protective functions."),
        GlossaryEntry(term: "Cépage", definition: "A French term for grape variety.", additionalInfo: "Often used in the context of labeling wines produced from one or more specific varietals."),
        GlossaryEntry(term: "Cultivar", definition: "A plant variety that has been produced in cultivation by selective breeding.", additionalInfo: "Commonly used in the context of viticulture for grape variety."),
        GlossaryEntry(term: "Demi-sec", definition: "A French term used to describe a semi-sweet wine, often a style of Champagne or sparkling wine.", additionalInfo: "Demi-sec wines are sweeter than brut but not as sweet as doux."),
        GlossaryEntry(term: "Elevage", definition: "The progression of wine between fermentation and bottling.", additionalInfo: "Comparable to the term 'raising' and often used to describe maturation processes in barrel or tank."),
        GlossaryEntry(term: "Fining", definition: "A process by which small particles in wine are coagulated and removed.", additionalInfo: "Agents like egg whites, gelatin, or bentonite may be used for this purpose."),
        GlossaryEntry(term: "Flor", definition: "A layer of yeast cells that develops on the surface of some wines during aging, notably in Sherry production.", additionalInfo: "Helps prevent oxidation and imparts unique flavors."),
        GlossaryEntry(term: "Green Harvest", definition: "The practice of removing unripe grape clusters to concentrate the energy and resources into the remaining fruit.", additionalInfo: "Aims to improve the quality of the harvest."),
        GlossaryEntry(term: "Herbaceous", definition: "Describes wines that exhibit flavors or aromas of green plants or grass.", additionalInfo: "Often associated with varieties like Sauvignon Blanc."),
        GlossaryEntry(term: "Ice Wine", definition: "A type of dessert wine produced from grapes that have been frozen while still on the vine.", additionalInfo: "The ice causes water to freeze inside the grape, concentrating the sugars and flavors."),
        GlossaryEntry(term: "Jug Wine", definition: "A term used for inexpensive bulk wine typically sold in large containers or jugs.", additionalInfo: "Associated with lower quality, everyday drinking wines."),
        GlossaryEntry(term: "Lieu-dit", definition: "A French term for a named place that signifies a smaller area within a larger region, recognized for its unique terroir.", additionalInfo: "Often appears on wine labels to denote specific vineyard sites."),
        GlossaryEntry(term: "Noble Varieties", definition: "Refers to grape varieties considered to be of the highest quality due to their historical pedigree and the premium wines they produce.", additionalInfo: "Examples include Cabernet Sauvignon, Merlot, Chardonnay, and Riesling."),
        GlossaryEntry(term: "Orange Wine", definition: "A type of wine made from white grape varieties where the grape skins are not removed, giving the wine an orange color.", additionalInfo: "This winemaking style imparts additional tannins and complexity."),
        GlossaryEntry(term: "Pétillant", definition: "A French term describing lightly sparkling wine.", additionalInfo: "Less effervescent than fully sparkling wines like Champagne."),
        GlossaryEntry(term: "Quinta", definition: "A Portuguese term for a wine estate.", additionalInfo: "Particularly used in the context of Port wine production."),
        GlossaryEntry(term: "Recioto", definition: "An Italian dessert wine made from grapes that have been dried to concentrate their juice.", additionalInfo: "A traditional wine style from the Veneto region."),
        GlossaryEntry(term: "Saignée", definition: "A method of rosé winemaking that involves 'bleeding' off a portion of red wine juice after it's had brief contact with the skins.", additionalInfo: "This technique concentrates the remaining red wines."),
        GlossaryEntry(term: "Vendange", definition: "The French term for grape harvest, particularly the picking of grapes during the harvest season.", additionalInfo: "A crucial time for winemakers, affecting the style and quality of the wine."),
        GlossaryEntry(term: "Weinbau", definition: "The German word for viticulture or winegrowing.", additionalInfo: "Encompasses all aspects of the grape growing process."),
        GlossaryEntry(term: "Xylem", definition: "Part of the vine’s vascular system, which transports water and nutrients from the roots to the rest of the vine.", additionalInfo: "Essential for healthy grape development."),
        GlossaryEntry(term: "Yield Management", definition: "A viticultural practice of controlling vineyard yields to produce higher quality grapes.", additionalInfo: "Often involves techniques like green harvesting."),
        GlossaryEntry(term: "Zesty", definition: "Describes wines with lively, vibrant, and sharp flavors, often attributed to high acidity.", additionalInfo: "Commonly used to describe certain white wines like Sauvignon Blanc."),
        GlossaryEntry(term: "Amarone", definition: "A rich, dry red wine from the Valpolicella region of Italy.", additionalInfo: "Made using the appassimento method, which involves drying the grapes before fermentation."),
        GlossaryEntry(term: "Anhydrous", definition: "A term describing a substance that contains no water.", additionalInfo: "In winemaking, it can refer to sulfur dioxide in its pure, water-free form."),
        GlossaryEntry(term: "Assemblage", definition: "The process of blending different wines to create a final product.", additionalInfo: "Commonly practiced in regions like Bordeaux."),
        GlossaryEntry(term: "Brut", definition: "A French term used to describe a dry Champagne or sparkling wine.", additionalInfo: "Indicates the wine has very low residual sugar."),
        GlossaryEntry(term: "Canopy Management", definition: "Techniques used to manage the growth of grapevine foliage.", additionalInfo: "Affects sunlight exposure, air circulation, and grape ripening."),
        GlossaryEntry(term: "Charmat Method", definition: "A method of sparkling wine production where secondary fermentation occurs in large tanks.", additionalInfo: "Used for wines like Prosecco."),
        GlossaryEntry(term: "Cold Stabilization", definition: "A process to prevent tartrate crystals from forming in wine bottles.", additionalInfo: "Involves chilling the wine before bottling."),
        GlossaryEntry(term: "Cuvée", definition: "A term used to denote a specific batch or blend of wine.", additionalInfo: "Often used in Champagne to refer to the blend used for sparkling wine."),
        GlossaryEntry(term: "Demeter", definition: "An organization that certifies biodynamic farms and products.", additionalInfo: "The Demeter label signifies adherence to biodynamic principles."),
        GlossaryEntry(term: "Dosage", definition: "A mixture of sugar and wine added to sparkling wine after disgorging.", additionalInfo: "Determines the wine's final sweetness level."),
        GlossaryEntry(term: "En Primeur", definition: "A method of purchasing wine while it is still in the barrel.", additionalInfo: "Common in Bordeaux, allowing buyers to secure sought-after wines early."),
        GlossaryEntry(term: "Garrigue", definition: "A type of Mediterranean scrubland with aromatic herbs and plants.", additionalInfo: "Wines from regions with garrigue often exhibit herbal notes."),
        GlossaryEntry(term: "Green Wine", definition: "Also known as Vinho Verde, a light and slightly effervescent wine from Portugal.", additionalInfo: "Often has a slight spritz and is meant to be consumed young."),
        GlossaryEntry(term: "Methode Ancestrale", definition: "An ancient method of making sparkling wine where the wine is bottled before primary fermentation is complete.", additionalInfo: "Results in a naturally sparkling wine."),
        GlossaryEntry(term: "MOG (Material Other than Grapes)", definition: "Any extraneous material that comes in with the grape harvest.", additionalInfo: "Includes leaves, stems, and debris."),
        GlossaryEntry(term: "Pip", definition: "A grape seed.", additionalInfo: "Contains tannins and can influence the bitterness of wine."),
        GlossaryEntry(term: "Pruning", definition: "The practice of trimming grapevines to control growth and improve fruit quality.", additionalInfo: "Affects the yield and quality of the grapes."),
        GlossaryEntry(term: "Ripasso", definition: "An Italian winemaking technique that involves re-fermenting Valpolicella wine with Amarone grape skins.", additionalInfo: "Produces a richer, more complex wine."),
        GlossaryEntry(term: "Sulfites", definition: "Sulfur compounds used in winemaking to prevent oxidation and spoilage.", additionalInfo: "Can cause allergic reactions in some people."),
        GlossaryEntry(term: "Vitis Vinifera", definition: "The species of grapevine most commonly used in winemaking.", additionalInfo: "Includes varieties like Cabernet Sauvignon, Chardonnay, and Merlot."),
        GlossaryEntry(term: "Acetaldehyde", definition: "A compound produced during fermentation that can cause off-flavors in wine if not managed properly.", additionalInfo: "Commonly associated with oxidative spoilage."),
        GlossaryEntry(term: "Bentonite", definition: "A type of clay used in winemaking for fining and clarifying wine.", additionalInfo: "Helps remove proteins and stabilize the wine."),
        GlossaryEntry(term: "Cross-Vintage Blending", definition: "Blending wines from different vintages to achieve a consistent style.", additionalInfo: "Commonly used in Champagne production."),
        GlossaryEntry(term: "Deacidification", definition: "The process of reducing acidity in wine.", additionalInfo: "Can be achieved through chemical or biological means."),
        GlossaryEntry(term: "Disgorging", definition: "The process of removing sediment from sparkling wine after secondary fermentation.", additionalInfo: "Usually done by freezing the neck of the bottle and removing the frozen plug."),
        GlossaryEntry(term: "Estate Grown", definition: "Indicates that the wine was made from grapes grown on the winery's own estate.", additionalInfo: "Similar to 'estate bottled' but emphasizes grape origin."),
        GlossaryEntry(term: "Field Blend", definition: "Wine made from different grape varieties that are harvested and fermented together.", additionalInfo: "Often results in a unique and complex wine."),
        GlossaryEntry(term: "Filtration", definition: "A process to remove solid particles and clarify wine.", additionalInfo: "Can be done using various methods, including membrane and diatomaceous earth filtration."),
        GlossaryEntry(term: "Grappa", definition: "A distilled spirit made from grape pomace.", additionalInfo: "Popular in Italy and often enjoyed as a digestif."),
        GlossaryEntry(term: "Must", definition: "Freshly crushed grape juice that contains the skins, seeds, and stems.", additionalInfo: "The starting point for fermentation in winemaking."),
        GlossaryEntry(term: "Punching Down", definition: "A winemaking process where the cap of skins formed during fermentation is pushed down into the juice.", additionalInfo: "Helps extract color, tannins, and flavors."),
        GlossaryEntry(term: "Stem Inclusion", definition: "The practice of including grape stems during fermentation.", additionalInfo: "Can add tannins and structure to the wine."),
        GlossaryEntry(term: "Tête de Cuvée", definition: "The finest wine of a particular producer, especially in Champagne.", additionalInfo: "Represents the top selection or best blend."),
        GlossaryEntry(term: "Trocken", definition: "A German term for dry wine.", additionalInfo: "Indicates that the wine has little to no residual sugar."),
        GlossaryEntry(term: "Vin Santo", definition: "A traditional Italian dessert wine made from dried grapes.", additionalInfo: "Known for its rich, sweet flavor and long aging potential."),
        GlossaryEntry(term: "Whole Cluster Fermentation", definition: "A winemaking technique where whole grape clusters, including stems, are fermented together.", additionalInfo: "Can add complexity and unique flavors to the wine."),
        GlossaryEntry(term: "Yeast Autolysis", definition: "The breakdown of dead yeast cells after fermentation.", additionalInfo: "Contributes to the texture and flavor of sparkling wines during aging."),
        GlossaryEntry(term: "Acetobacter", definition: "A genus of bacteria that converts alcohol into acetic acid, causing wine spoilage.", additionalInfo: "Can result in vinegar-like off-flavors."),
        GlossaryEntry(term: "Aeration", definition: "The process of exposing wine to air to soften tannins and release aromas.", additionalInfo: "Often done through decanting or swirling the glass."),
        GlossaryEntry(term: "Aging", definition: "The process of maturing wine in barrels, tanks, or bottles.", additionalInfo: "Affects the flavor, aroma, and texture of wine."),
        GlossaryEntry(term: "Amelioration", definition: "The addition of water and sugar to grape juice before fermentation.", additionalInfo: "Used to balance acidity and increase alcohol content."),
        GlossaryEntry(term: "Anthocyanins", definition: "Pigments in grape skins that give red wine its color.", additionalInfo: "Also contribute to the wine's antioxidant properties."),
        GlossaryEntry(term: "Autolysis", definition: "The breakdown of dead yeast cells releasing flavors and textures into the wine.", additionalInfo: "Common in sparkling wine production."),
        GlossaryEntry(term: "Barrel Fermentation", definition: "Fermenting wine directly in oak barrels.", additionalInfo: "Impacts the flavor and texture of the wine."),
        GlossaryEntry(term: "Barrel Toasting", definition: "The process of charring the inside of oak barrels to varying degrees.", additionalInfo: "Influences the flavor profile of the wine."),
        GlossaryEntry(term: "Body", definition: "The weight and fullness of wine on the palate.", additionalInfo: "Can be light, medium, or full-bodied."),
        GlossaryEntry(term: "Bordeaux Mixture", definition: "A fungicide made from copper sulfate and lime used to control mildew in vineyards.", additionalInfo: "Widely used in organic viticulture."),
        GlossaryEntry(term: "Bouchon", definition: "A French term for a wine cork.", additionalInfo: "Also refers to a type of restaurant in Lyon."),
        GlossaryEntry(term: "Breathing", definition: "Allowing wine to aerate by exposing it to air.", additionalInfo: "Helps to open up the wine's aromas and flavors."),
        GlossaryEntry(term: "Bricking", definition: "The term used to describe the color change in red wine as it ages.", additionalInfo: "Indicates aging and oxidation."),
        GlossaryEntry(term: "Cap", definition: "The layer of skins and solids that forms during red wine fermentation.", additionalInfo: "Needs to be managed through punching down or pumping over."),
        GlossaryEntry(term: "Carbonic Acid", definition: "A weak acid formed in wine when carbon dioxide dissolves in water.", additionalInfo: "Affects the wine's pH and acidity."),
        GlossaryEntry(term: "Chalky", definition: "A tasting note indicating a texture or flavor reminiscent of chalk.", additionalInfo: "Often found in wines from limestone-rich soils."),
        GlossaryEntry(term: "Clonal Selection", definition: "The process of selecting grapevine clones for specific desired traits.", additionalInfo: "Improves consistency and quality in vineyards."),
        GlossaryEntry(term: "Concrete Egg", definition: "A type of fermentation vessel made from concrete shaped like an egg.", additionalInfo: "Promotes natural convection currents and consistent fermentation."),
        GlossaryEntry(term: "Coquard Press", definition: "A traditional Champagne press used to gently extract juice from grapes.", additionalInfo: "Preserves delicate flavors and aromas."),
        GlossaryEntry(term: "Cuverie", definition: "A French term for a winery or wine production facility.", additionalInfo: "Includes fermentation tanks and other winemaking equipment."),
        GlossaryEntry(term: "Diacetyl", definition: "A compound produced during malolactic fermentation that gives a buttery aroma.", additionalInfo: "Common in some Chardonnays."),
        GlossaryEntry(term: "Double Magnum", definition: "A large wine bottle holding 3 liters, equivalent to four standard bottles.", additionalInfo: "Often used for special events and aging."),
        GlossaryEntry(term: "Earthy", definition: "A tasting note indicating flavors or aromas reminiscent of soil or earth.", additionalInfo: "Can be a positive attribute in moderation."),
        GlossaryEntry(term: "Enzyme", definition: "Proteins used in winemaking to break down grape components and aid fermentation.", additionalInfo: "Helps to clarify and stabilize wine."),
        GlossaryEntry(term: "Eutypa Dieback", definition: "A fungal disease that causes dieback and reduced yields in grapevines.", additionalInfo: "Requires careful vineyard management to control."),
        GlossaryEntry(term: "Foxy", definition: "A tasting note often associated with wines made from Vitis labrusca grapes.", additionalInfo: "Describes a musky or grapey flavor."),
        GlossaryEntry(term: "Fruit Set", definition: "The stage in the vine's lifecycle when flowers develop into grape berries.", additionalInfo: "Critical for determining the potential yield of the harvest."),
        GlossaryEntry(term: "Glycerol", definition: "A byproduct of fermentation that adds sweetness and body to wine.", additionalInfo: "Contributes to the wine's mouthfeel."),
        GlossaryEntry(term: "Isinglass", definition: "A fining agent derived from fish bladders used to clarify wine.", additionalInfo: "Helps to remove solids and improve stability."),
        GlossaryEntry(term: "Kosher Wine", definition: "Wine made according to Jewish dietary laws and supervised by a rabbi.", additionalInfo: "Must be handled and produced by Sabbath-observant Jews."),
        GlossaryEntry(term: "Lactic Acid", definition: "An acid produced during malolactic fermentation that softens wine acidity.", additionalInfo: "Contributes to a rounder, smoother mouthfeel."),
        GlossaryEntry(term: "Lactic Bacteria", definition: "Bacteria responsible for converting malic acid to lactic acid in wine.", additionalInfo: "Plays a key role in malolactic fermentation."),
        GlossaryEntry(term: "Lees Contact", definition: "Aging wine on its lees to enhance flavors and textures.", additionalInfo: "Common in sparkling wines and some whites."),
        GlossaryEntry(term: "Lysozyme", definition: "An enzyme used to control lactic acid bacteria in winemaking.", additionalInfo: "Helps to prevent spoilage and maintain wine stability."),
        GlossaryEntry(term: "Micro-Oxygenation", definition: "A technique of introducing controlled amounts of oxygen into wine.", additionalInfo: "Can soften tannins and improve aging potential."),
        GlossaryEntry(term: "Must Weight", definition: "A measure of the sugar content in grape juice before fermentation.", additionalInfo: "Indicates potential alcohol content of the finished wine."),
        GlossaryEntry(term: "Organic Wine", definition: "Wine made from grapes grown without synthetic pesticides or fertilizers.", additionalInfo: "Must adhere to organic certification standards."),
        GlossaryEntry(term: "Oxidative Winemaking", definition: "A style of winemaking that intentionally exposes wine to oxygen.", additionalInfo: "Produces wines with unique flavors and aromas."),
        GlossaryEntry(term: "Pierce's Disease", definition: "A bacterial disease that affects grapevines, causing vine death.", additionalInfo: "Spread by insect vectors and difficult to control."),
        GlossaryEntry(term: "Press Fraction", definition: "The different portions of juice extracted during pressing.", additionalInfo: "Includes free-run juice and pressed juice, each with different qualities."),
        GlossaryEntry(term: "Primary Fermentation", definition: "The initial stage of fermentation where yeast converts sugars to alcohol.", additionalInfo: "Produces most of the wine's alcohol and initial flavors."),
        GlossaryEntry(term: "Pumping Over", definition: "A winemaking process that involves pumping wine over the cap of skins during fermentation.", additionalInfo: "Helps extract color, tannins, and flavors."),
        GlossaryEntry(term: "Quercus Alba", definition: "The scientific name for American white oak, commonly used in barrel making.", additionalInfo: "Imparts distinct flavors to wine during aging."),
        GlossaryEntry(term: "Rootstock", definition: "The root part of a grafted vine onto which the scion is grafted.", additionalInfo: "Chosen for disease resistance and compatibility with soil."),
        GlossaryEntry(term: "Sap", definition: "The watery fluid that circulates through a vine's vascular system.", additionalInfo: "Transports nutrients and water to the vine."),
        GlossaryEntry(term: "Scion", definition: "The upper part of a grafted vine that is selected for its fruiting qualities.", additionalInfo: "Grafted onto a rootstock."),
        GlossaryEntry(term: "Sec", definition: "A French term meaning 'dry', often used to describe Champagne.", additionalInfo: "Indicates a lower level of sweetness."),
        GlossaryEntry(term: "Semi-Carbonic Maceration", definition: "A winemaking technique where whole grapes are fermented in a carbon dioxide-rich environment without adding CO2.", additionalInfo: "Produces fruity, low-tannin wines."),
        GlossaryEntry(term: "Skin Contact", definition: "The process of allowing grape skins to remain in contact with the juice during fermentation.", additionalInfo: "Extracts color, tannins, and flavors."),
        GlossaryEntry(term: "Sparkling Wine", definition: "Wine that contains dissolved carbon dioxide, making it fizzy.", additionalInfo: "Includes Champagne, Prosecco, and Cava."),
        GlossaryEntry(term: "Spontaneous Fermentation", definition: "Fermentation initiated by wild yeast naturally present on the grapes or in the winery.", additionalInfo: "Can produce unique and complex flavors."),
        GlossaryEntry(term: "Stave", definition: "A narrow length of wood used to make barrels.", additionalInfo: "Staves are curved and assembled to form the barrel."),
        GlossaryEntry(term: "Stomata", definition: "Tiny openings on the surface of vine leaves that allow gas exchange.", additionalInfo: "Important for photosynthesis and transpiration."),
        GlossaryEntry(term: "Sulfite-Free Wine", definition: "Wine made without the addition of sulfur dioxide.", additionalInfo: "May still contain naturally occurring sulfites."),
        GlossaryEntry(term: "Tirage", definition: "The process of bottling the base wine with a mixture of sugar and yeast to initiate secondary fermentation in sparkling wine production.", additionalInfo: "Creates the bubbles in sparkling wine."),
        GlossaryEntry(term: "Traditional Method", definition: "A method of sparkling wine production where secondary fermentation occurs in the bottle.", additionalInfo: "Used in Champagne and other quality sparkling wines."),
        GlossaryEntry(term: "Vascular Bundle", definition: "A part of the vine's vascular system that includes xylem and phloem.", additionalInfo: "Transports water, nutrients, and sugars."),
        GlossaryEntry(term: "Wine Diamonds", definition: "Crystalline deposits of tartaric acid that can form in wine bottles.", additionalInfo: "Harmless but can be removed by cold stabilization."),
        GlossaryEntry(term: "Yeast Assimilable Nitrogen (YAN)", definition: "The amount of nitrogen available for yeast during fermentation.", additionalInfo: "Critical for healthy fermentation."),
        GlossaryEntry(term: "Yeast Hulls", definition: "Dead yeast cells added to fermenting wine to provide nutrients.", additionalInfo: "Can help restart a stuck fermentation."),
        GlossaryEntry(term: "Piccolo", definition: "A small wine bottle with a capacity of 187.5 ml, equivalent to a quarter of a standard bottle.", additionalInfo: "Often used for individual servings of Champagne."),
        GlossaryEntry(term: "Demi", definition: "A wine bottle with a capacity of 375 ml, equivalent to half of a standard bottle.", additionalInfo: "Commonly used for dessert wines and sparkling wines."),
        GlossaryEntry(term: "Jennie", definition: "A wine bottle with a capacity of 500 ml, typically used for sweet wines.", additionalInfo: "Also known as 'half-liter' bottle."),
        GlossaryEntry(term: "Standard", definition: "The most common wine bottle size with a capacity of 750 ml.", additionalInfo: "Used for most still and sparkling wines."),
        GlossaryEntry(term: "Magnum", definition: "A wine bottle with a capacity of 1.5 liters, equivalent to 2 standard bottles.", additionalInfo: "Preferred for aging wine as it has a better air-to-wine ratio."),
        GlossaryEntry(term: "Jeroboam",
            definition: "A large wine bottle with variable capacities depending on the region: 3 liters (4 standard bottles) in Champagne and Burgundy; 5 liters (6.67 standard bottles) in Bordeaux.",
            additionalInfo: "The term 'Jeroboam' is used to denote larger bottle sizes typically used for celebrations. The capacity varies significantly between key wine-producing regions, reflecting different local traditions."),
        GlossaryEntry(term: "Rehoboam", definition: "A wine bottle with a capacity of 4.5 liters, equivalent to 6 standard bottles, used for sparkling wine.", additionalInfo: "Named after a biblical king."),
        GlossaryEntry(term: "Methuselah/Imperial",
            definition: "A large wine bottle with a capacity of 6 liters, equivalent to 8 standard bottles.",
            additionalInfo: "The term 'Methuselah' is commonly used in Champagne and Burgundy, while 'Imperial' is used for the same size bottle in Bordeaux. This size is preferred for aging wine due to its better air-to-wine ratio."),
        GlossaryEntry(term: "Salmanazar", definition: "A wine bottle with a capacity of 9 liters, equivalent to 12 standard bottles.", additionalInfo: "Named after an Assyrian king."),
        GlossaryEntry(term: "Balthazar", definition: "A wine bottle with a capacity of 12 liters, equivalent to 16 standard bottles.", additionalInfo: "Named after one of the Three Wise Men."),
        GlossaryEntry(term: "Nebuchadnezzar", definition: "A wine bottle with a capacity of 15 liters, equivalent to 20 standard bottles.", additionalInfo: "Named after a Babylonian king."),
        GlossaryEntry(term: "Melchior", definition: "A wine bottle with a capacity of 18 liters, equivalent to 24 standard bottles.", additionalInfo: "Named after one of the Three Wise Men."),
        GlossaryEntry(term: "Solomon", definition: "A wine bottle with a capacity of 18 liters, equivalent to 24 standard bottles, less common.", additionalInfo: "Named after a biblical king."),
        GlossaryEntry(term: "Sovereign", definition: "A wine bottle with a capacity of 25 liters, equivalent to 33.33 standard bottles.", additionalInfo: "One of the largest wine bottle sizes available."),
        GlossaryEntry(term: "Goliath/Primat",
            definition: "A wine bottle with a capacity of 27 liters, equivalent to 36 standard bottles.",
            additionalInfo: "The terms 'Goliath' and 'Primat' are used interchangeably based on regional or traditional preferences, primarily for large celebrations or events."),
        GlossaryEntry(term: "Melchizedek", definition: "A wine bottle with a capacity of 30 liters, equivalent to 40 standard bottles.", additionalInfo: "Named after a biblical figure."),
        GlossaryEntry(term: "Autovinifier", definition: "A fermentation vessel that uses natural pressure from carbon dioxide to pump over the fermenting must, often used in making red wines.", additionalInfo: "Autovinifiers are commonly used in regions with warm climates."),
        GlossaryEntry(term: "Cap Management", definition: "Techniques used to manage the cap of skins, seeds, and stems that forms during red wine fermentation.", additionalInfo: "Effective cap management is crucial for color and tannin extraction."),
        GlossaryEntry(term: "Carbonic Maceration", definition: "A winemaking technique where whole grapes ferment in a carbon dioxide-rich environment before crushing.", additionalInfo: "This method produces fruity, low-tannin wines."),
        GlossaryEntry(term: "Cold Soak", definition: "A pre-fermentation maceration technique to extract color and flavor compounds from grape skins.", additionalInfo: "Cold soaking can enhance the complexity of red wines."),
        GlossaryEntry(term: "Cordon", definition: "A method of training grapevines where the vine's arms are trained horizontally.", additionalInfo: "Cordon training helps to optimize sun exposure and air circulation."),
        GlossaryEntry(term: "Demijohn", definition: "A large glass vessel used for fermenting and aging wine.", additionalInfo: "Demijohns are often used for home winemaking."),
        GlossaryEntry(term: "Disgorgement", definition: "The process of removing sediment from sparkling wine after secondary fermentation in the bottle.", additionalInfo: "This step is essential for producing clear, sparkling wines."),
        GlossaryEntry(term: "Qvevri", definition: "Large clay vessels traditionally used in Georgian winemaking for fermenting and aging wine.", additionalInfo: "Qvevri are buried underground to maintain a stable temperature."),
        GlossaryEntry(term: "Récolte", definition: "A French term for 'harvest,' referring to the grape harvest season.", additionalInfo: "The timing of the récolte can greatly influence the wine's characteristics."),
        GlossaryEntry(term: "Ampelography", definition: "The study and identification of grapevines, typically through the analysis of leaves, shoots, and grape clusters.", additionalInfo: "Used to classify and differentiate grape varieties."),
        GlossaryEntry(term: "Astringency", definition: "The dry, puckering mouthfeel caused by tannins in wine.", additionalInfo: "Common in young red wines and certain white wines."),
        GlossaryEntry(term: "Baumé", definition: "A scale used to measure the sugar content of grape juice or wine, indicating potential alcohol content.", additionalInfo: "Named after French chemist Antoine Baumé."),
        GlossaryEntry(term: "Biodiversity", definition: "The variety of plant and animal life in a particular habitat, important for sustainable viticulture.", additionalInfo: "Promotes ecosystem health and resilience."),
        GlossaryEntry(term: "Blending", definition: "The process of combining different wines to create a final product with desired characteristics.", additionalInfo: "Blending can enhance complexity and balance."),
        GlossaryEntry(term: "Brut Nature", definition: "A very dry style of sparkling wine with no added dosage (sugar).", additionalInfo: "Also known as 'zero dosage' or 'brut zero'."),
        GlossaryEntry(term: "Carbonation", definition: "The process of adding carbon dioxide to wine to create bubbles, as in sparkling wine.", additionalInfo: "Can be done naturally or artificially."),
        GlossaryEntry(term: "Clarification", definition: "The process of removing suspended particles from wine to make it clear, often using fining agents or filtration.", additionalInfo: "Essential for stability and appearance."),
        GlossaryEntry(term: "Coulure", definition: "A viticultural hazard that causes poor fruit set and results in fewer berries on grape clusters.", additionalInfo: "Caused by unfavorable weather conditions."),
        GlossaryEntry(term: "Diurnal Range", definition: "The difference between daytime and nighttime temperatures, which can affect grape ripening and wine quality.", additionalInfo: "Wider diurnal ranges can enhance acidity and complexity."),
        GlossaryEntry(term: "En tirage", definition: "The period during which sparkling wine matures on its lees after secondary fermentation in the bottle.", additionalInfo: "Adds complexity and texture to the wine."),
        GlossaryEntry(term: "Glycol", definition: "A chemical compound sometimes used illegally to sweeten or thicken wine.", additionalInfo: "Its use in winemaking is prohibited due to health risks."),
        GlossaryEntry(term: "Integrated Pest Management (IPM)", definition: "A sustainable approach to managing pests in vineyards using a combination of biological, cultural, and chemical methods.", additionalInfo: "Reduces reliance on chemical pesticides."),
        GlossaryEntry(term: "Lutte Raisonnée", definition: "A French term for 'reasoned struggle,' referring to a pragmatic approach to vineyard management that reduces chemical use.", additionalInfo: "Emphasizes observation and minimal intervention."),
        GlossaryEntry(term: "Noble Rot", definition: "Another term for Botrytis cinerea, a beneficial fungus that concentrates sugars in grapes, used to produce sweet wines.", additionalInfo: "Essential for wines like Sauternes and Tokaji."),
        GlossaryEntry(term: "Phenolic Compounds", definition: "Chemical compounds in grapes that affect the taste, color, and mouthfeel of wine, including tannins and anthocyanins.", additionalInfo: "Important for wine structure and aging potential."),
        GlossaryEntry(term: "Sulfur Dioxide (SO2)", definition: "A preservative and antioxidant used in winemaking to prevent oxidation and spoilage.", additionalInfo: "SO2 is essential for maintaining wine stability and longevity."),
        GlossaryEntry(term: "Teinturier", definition: "A type of grape with red flesh and juice, used to add color to wine blends.", additionalInfo: "Examples include Alicante Bouschet and Saperavi."),
        GlossaryEntry(term: "Trellising", definition: "A system of training grapevines on a framework of stakes and wires to optimize sun exposure and air circulation.", additionalInfo: "Improves grape quality and vineyard management."),
        GlossaryEntry(term: "Volatile Acidity (VA)", definition: "The measure of volatile acids, primarily acetic acid, in wine that can contribute to spoilage if levels are too high.", additionalInfo: "Low levels can add complexity, but high levels are considered a fault."),
        GlossaryEntry(term: "Barrique", definition: "A type of oak barrel traditionally used for aging wine, particularly in Bordeaux.", additionalInfo: "It typically holds 225 liters."),
        GlossaryEntry(term: "Puncheon", definition: "A large barrel used for aging wine, typically holding around 500 liters.", additionalInfo: "Larger than a barrique, it imparts less oak flavor to the wine."),
        GlossaryEntry(term: "Hogshead", definition: "A large barrel used for aging wine, typically holding around 300 liters.", additionalInfo: "Commonly used in Australia."),
        GlossaryEntry(term: "Pipe", definition: "A barrel used primarily for aging Port wine, traditionally holding 550 to 600 liters.", additionalInfo: "The size can vary depending on the region."),
        GlossaryEntry(term: "Butt", definition: "A large barrel used for aging Sherry, typically holding 500 liters.", additionalInfo: "Also used for other types of fortified wines."),
        GlossaryEntry(term: "Gonc", definition: "A barrel used in Hungary for aging Tokaji wine, typically holding 136 liters.", additionalInfo: "Unique to the Tokaji wine region."),
        GlossaryEntry(term: "Foudre", definition: "A very large wooden vat used for aging wine, often holding several thousand liters.", additionalInfo: "Commonly used in the Rhône Valley and Alsace."),
        GlossaryEntry(term: "Quarter Cask", definition: "A smaller barrel used for aging wine or spirits, typically holding around 50 liters.", additionalInfo: "Allows for quicker aging due to the higher surface area to volume ratio."),
        GlossaryEntry(term: "Tonneau", definition: "A barrel used for aging wine, typically holding around 900 liters.", additionalInfo: "Used historically in Bordeaux."),
        GlossaryEntry(term: "Cognac Barrel", definition: "A barrel used for aging Cognac, typically holding around 350 liters.", additionalInfo: "Made from French oak and used exclusively in the Cognac region."),
        GlossaryEntry(term: "Oxidative Spoilage", definition: "The process that occurs when wine is exposed to oxygen, leading to undesirable changes in flavor and aroma.", additionalInfo: "Oxidative spoilage can result in the wine becoming flat, brown, and vinegar-like."),
            GlossaryEntry(term: "Acetic Acid", definition: "A type of acid found in wine that gives it a sour taste.", additionalInfo: "Acetic acid is produced by the oxidation of ethanol and is the main component of vinegar."),
            GlossaryEntry(term: "Structure", definition: "The overall architecture of a wine's components, including acidity, tannins, alcohol, and body.", additionalInfo: "A well-structured wine has a balanced and harmonious combination of these elements."),
            GlossaryEntry(term: "Swirling", definition: "The act of moving wine around in a glass to release its aromas.", additionalInfo: "Swirling helps to aerate the wine and enhance the sensory experience."),
            GlossaryEntry(term: "Flavor", definition: "The combination of taste and aroma that wine presents.", additionalInfo: "Flavor encompasses all the sensory characteristics that come from the grape, fermentation process, and aging."),
            GlossaryEntry(term: "Texture", definition: "The way wine feels in the mouth, often described as smooth, rough, or velvety.", additionalInfo: "Texture is influenced by factors such as tannins, alcohol content, and the wine-making process."),
            GlossaryEntry(term: "Maturing", definition: "The process by which wine develops and evolves over time in a bottle or barrel.", additionalInfo: "Maturing can enhance the complexity and depth of flavors in a wine."),
            GlossaryEntry(term: "Alcohol Content", definition: "The percentage of alcohol in wine, typically ranging from 8% to 15% by volume.", additionalInfo: "Alcohol content affects the body, flavor, and overall balance of a wine."),
            GlossaryEntry(term: "Evaporation", definition: "The process by which liquid wine is lost to the atmosphere, particularly during aging.", additionalInfo: "Evaporation can concentrate the remaining components of the wine, enhancing its flavor."),
            GlossaryEntry(term: "Pigments", definition: "Natural compounds that give wine its color.", additionalInfo: "Pigments come from the grape skins and can be affected by factors such as grape variety and winemaking techniques."),
            GlossaryEntry(term: "Antioxidant", definition: "Compounds that prevent oxidation and spoilage in wine.", additionalInfo: "Common antioxidants in wine include sulfur dioxide and ascorbic acid."),
            GlossaryEntry(term: "Fruity", definition: "A flavor profile that suggests the presence of fruit flavors.", additionalInfo: "Fruity wines can have notes of berries, citrus, stone fruits, or tropical fruits."),
            GlossaryEntry(term: "Floral", definition: "Aromatic notes that resemble flowers.", additionalInfo: "Floral aromas can be found in many white wines and some light red wines."),
            GlossaryEntry(term: "Vessel", definition: "The container used for fermenting or aging wine.", additionalInfo: "Common vessels include stainless steel tanks, oak barrels, and concrete tanks."),
            GlossaryEntry(term: "Color Transfer", definition: "The process by which color is extracted from grape skins into the wine.", additionalInfo: "This occurs during maceration and fermentation, affecting the wine's final hue."),
            GlossaryEntry(term: "Complexity", definition: "The range and depth of flavors and aromas in a wine.", additionalInfo: "A complex wine offers multiple layers of sensory experiences and evolves over time."),
            GlossaryEntry(term: "Weight", definition: "The perceived heaviness or fullness of wine in the mouth.", additionalInfo: "Weight is influenced by factors such as alcohol content, sugar levels, and tannin concentration."),
            GlossaryEntry(term: "Medium Bodied", definition: "A wine that has a moderate weight and richness.", additionalInfo: "Medium-bodied wines strike a balance between light and full-bodied wines."),
            GlossaryEntry(term: "Light Bodied", definition: "A wine that feels lighter and more delicate in the mouth.", additionalInfo: "Light-bodied wines are often lower in alcohol and have a higher acidity."),
            GlossaryEntry(term: "Full Bodied", definition: "A wine that feels rich, heavy, and dense in the mouth.", additionalInfo: "Full-bodied wines typically have higher alcohol content and more intense flavors."),
            GlossaryEntry(term: "Wine Closure", definition: "The method used to seal a wine bottle.", additionalInfo: "Common closures include corks, screw caps, and synthetic stoppers."),
            GlossaryEntry(term: "Vitner", definition: "A person who makes or sells wine.", additionalInfo: "Vitners are involved in the production and commercialization of wine."),
            GlossaryEntry(term: "Clone", definition: "A grapevine that is genetically identical to the original plant.", additionalInfo: "Cloning allows for the replication of desirable grapevine characteristics."),
            GlossaryEntry(term: "Doux", definition: "A French term meaning 'sweet', used to describe wines with a high sugar content.", additionalInfo: "Doux wines are often dessert wines and can be very rich and luscious."),
            GlossaryEntry(term: "Dieback", definition: "The decline or death of grapevine branches or shoots.", additionalInfo: "Dieback can be caused by disease, pests, or environmental stress."),
            GlossaryEntry(term: "Membrane Filtration", definition: "A technique used to clarify and stabilize wine by removing unwanted particles.", additionalInfo: "Membrane filtration can improve the clarity and shelf life of the wine."),
            GlossaryEntry(term: "Diatomaceous Earth Filtration", definition: "A filtration process that uses diatomaceous earth to remove impurities from wine.", additionalInfo: "This method is effective in clarifying wine without affecting its flavor."),
            GlossaryEntry(term: "Macroclimate", definition: "The climate of a large geographic area affecting viticulture.", additionalInfo: "Macroclimate influences grape growing conditions over a broad region."),
            GlossaryEntry(term: "Grafting", definition: "The practice of joining two grapevine parts together so they grow as one plant.", additionalInfo: "Grafting is used to improve disease resistance and adapt to different soil types."),
            GlossaryEntry(term: "Phloem", definition: "The vascular tissue in plants responsible for transporting nutrients.", additionalInfo: "In grapevines, phloem distributes the sugars produced by photosynthesis."),
            GlossaryEntry(term: "Mesoclimate", definition: "The climate of a specific vineyard or vineyard area.", additionalInfo: "Mesoclimate can significantly influence the characteristics of the grapes and resulting wine.")
        
                      
                      
        ]
        }
